version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=claude_mvc_app
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your-secret-key-here
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  app-dev:
    build: .
    command: npm run dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./.env:/app/.env
    profiles:
      - dev

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=claude_mvc_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: