/**
 * TestControllerController
 * 
 * Generated by MVC CLI
 */
class TestControllerController {
  /**
   * indexアクション
   */
  async index(req, res, next) {
    try {
      // TODO: indexの実装
      res.render('testcontroller/index', {
        title: 'index'
      });
    } catch (error) {
      next(error);
    }
  }
}

module.exports = new TestControllerController();