version: '3.8'

services:
  app-test:
    build: 
      context: ../../
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=test
      - DB_HOST=db-test
      - DB_PORT=5432
      - DB_NAME=mvc_test
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - JWT_SECRET=test_jwt_secret_key_minimum_32_chars
      - JWT_REFRESH_SECRET=test_refresh_secret_key_minimum_32_chars
    depends_on:
      - db-test
      - redis-test
    volumes:
      - ../../:/app
      - /app/node_modules
      - ./.env:/app/.env
    command: npm test
    
  db-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mvc_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    
  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --save ""