const { DataTypes } = require('sequelize');

/**
 * TestModelモデル
 * 
 * Generated by MVC CLI
 */
module.exports = (sequelize) => {
  const TestModel = sequelize.define('TestModel', {

  }, {
    tableName: 'test_models',
    timestamps: true,
    paranoid: false,
    underscored: true,
    indexes: [
      // インデックスの定義
      
    ]
  });

  // アソシエーションの定義
  TestModel.associate = (models) => {
    TestModel.belongsTo(models.User, {
      foreignKey: 'userId',
      as: 'user'
    });
  };

  

    // JSONレスポンス用のフォーマット
  TestModel.prototype.toJSON = function() {
    const values = { ...this.get() };
    
    // パスワードなどのセンシティブな情報を除外
    delete values.password;
    delete values.deletedAt;
    
    return values;
  };

    // 検索メソッド
  TestModel.search = async function(query, options = {}) {
    const { page = 1, limit = 10 } = options;
    
    return this.findAndCountAll({
      where: {
        // TODO: 検索条件の実装
      },
      limit,
      offset: (page - 1) * limit,
      order: [['createdAt', 'DESC']]
    });
  };

  return TestModel;
};